//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Table_1
{
    public int BestellingID { get; set; }
    public System.DateTime DatumOpgemaakt { get; set; }
    public int PersoneelidID { get; set; }
    public int LeverancierID { get; set; }
    public int KlantID { get; set; }
    public System.DateTime DatumVerzending { get; set; }
    public System.DateTime DatumAankomst { get; set; }
}
